var opportunity="This is test sample3";
var customer="This is test Sample4";
var entity="This is sample field information";
var subpractice="This is sample field information";
var practice="This is sample field information";
var gbu="This is sample field information";
var requirementtype="This is sample field information";
var clientrate="This is sample field information";
var infrastructure="This is sample field information";
var employeerole="This is sample field information";
var designation="This is sample field information";
var roleband="This is sample field information";
var typeofassignment="This is sample field information";
var employemnttype="This is sample field information";
var positiontype="This is sample field information";
var requirementpercentage="This is sample field information";
var requirementstartdate="This is sample field information";
var requirementenddate="This is sample field information";
var primaryskill="This is sample field information";
var secondryskill="This is sample field information";
var clientinterviewreq="This is sample field information";
var industry="This is sample field information";
var industryexp="This is sample field information";
var minrelevantexp="This is sample field information";
var natureofvacancy="This is sample field information";
var replacementfor="This is sample field information";
var salaryrange="This is sample field information";
var worklocation="This is sample field information";
var baselocation="This is sample field information";
var durationofonsite="This is sample field information";
var reportingto="This is sample field information";
var clientpartner="This is sample field information";
var projectmanager="This is sample field information";
var fpnaapprover="This is sample field information";
var rmospoc="This is sample field information";
var jobsummary="This is sample field information";
var jobdescription="This is sample field information";
var supportfile="This is sample field information";



function assigntooltipvalue()
{
$("#lbloppertunitystatus i").attr("title",opportunity);
$("#lblcustomer i").attr("title",customer);
$("#lblentity i").attr("title",entity);
$("#lblsubpractice i").attr("title",subpractice);
$("#lblpractice i").attr("title",practice);
$("#lblgbu i").attr("title",gbu);
$("#lblrequirementtype i").attr("title",requirementtype);
$("#lblclientrate i").attr("title",clientrate);
$("#Label1 i").attr("title",infrastructure);
$("#lblemployeerole i").attr("title",employeerole);
$("#lbldesignation i").attr("title",designation);
$("#lblroleband i").attr("title",roleband);
$("#lbltypeofassignemnt i").attr("title",typeofassignment);
$("#lblemploymenttype i").attr("title",employemnttype);
$("#lblpositiontype i").attr("title",positiontype);
$("#lblrequirementpercentage i").attr("title",requirementpercentage);
$("#lblrequirementstartdate i").attr("title",requirementstartdate);
$("#lblrequirementenddat i").attr("title",requirementenddate);
$("#lblprimaryskill i").attr("title",primaryskill);
$("#lblsecondryskill i").attr("title",secondryskill);
$("#lblclientinterviewrequired i").attr("title",clientinterviewreq);
$("#lblindustry i").attr("title",industry);
$("#lblindustryexperiance i").attr("title",industryexp);
$("#lblminrelevantexp i").attr("title",minrelevantexp);
$("#lblnatureofvacancy i").attr("title",natureofvacancy);
$("#lblreplacementfor i").attr("title",replacementfor);
$("#lblsalaryrange i").attr("title",salaryrange);
$("#lblworklocation i").attr("title",worklocation);
$("#lblbaselocation i").attr("title",baselocation);
$("#lbldurationofonsitetravel i").attr("title",durationofonsite);
$("#lblreportingto i").attr("title",reportingto);
$("#lblclientpartner i").attr("title",clientpartner);
$("#lblprojectmanager i").attr("title",projectmanager);
$("#lblfpaapprover i").attr("title",fpnaapprover);
$("#lblrmospoc i").attr("title",rmospoc);
$("#lbljobsummary i").attr("title",jobsummary);
$("#Label2 i").attr("title",jobdescription);
$("#lbluploadsupport i").attr("title",supportfile);
}